[tool.black]
line-length = 120
target-version = ["py311"]

[tool.isort]
py_version = 37
skip = [
    "__init__.py",
    "middlewares.py",
    "chatConsumer.py",
]
multi_line_output = 3
include_trailing_comma = true

[tool.mypy]
python_version = "3.11"
no_namespace_packages = true
no_strict_optional = true
