# Generated by Django 5.0.7 on 2024-08-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nickname",
            field=models.CharField(
                default="admin", help_text="Required.", max_length=8, unique=True, verbose_name="Nickname"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="picture",
            field=models.ImageField(blank=True, help_text="Optional.", upload_to="", verbose_name="Picture"),
        ),
    ]
