# Generated by Django 5.0.7 on 2024-08-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_nickname_customuser_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="users/profile-default.png",
                help_text="Optional.",
                upload_to="users/",
                verbose_name="Picture",
            ),
        ),
    ]
