# Generated by Django 5.1 on 2024-08-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="picture",
            field=models.ImageField(
                default="users/profile-default.png",
                help_text="Required.",
                upload_to="users/profile/",
                verbose_name="Picture",
            ),
        ),
    ]
