# Generated by Django 5.1 on 2024-08-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_friends_customuser_followings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="followings",
        ),
    ]
