# Generated by Django 5.1 on 2024-08-15 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_customuser_followings"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="followings",
            field=models.ManyToManyField(blank=True, related_name="followers", to=settings.AUTH_USER_MODEL),
        ),
    ]
