# Generated by Django 5.1 on 2024-08-19 05:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_customuser_followings"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="blocks",
            field=models.ManyToManyField(blank=True, related_name="blocked", to=settings.AUTH_USER_MODEL),
        ),
    ]
