# Generated by Django 5.1 on 2024-08-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_customuser_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="lose",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="win",
            field=models.IntegerField(default=0),
        ),
    ]
