# Generated by Django 5.1 on 2024-08-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_customuser_lose_customuser_win"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.IntegerField(choices=[(0, "Disconnected"), (1, "Connected"), (2, "Playing")], default=0),
        ),
    ]
