# Generated by Django 5.1 on 2024-08-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_customuser_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
