# Generated by Django 5.1 on 2024-08-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_alter_customuser_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.IntegerField(choices=[(0, "Disconnected"), (1, "Connected"), (2, "Playing")], default=0),
        ),
    ]
