# Generated by Django 5.1 on 2024-08-20 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("game_type", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("losers", models.ManyToManyField(blank=True, related_name="lost_games", to=settings.AUTH_USER_MODEL)),
                ("winners", models.ManyToManyField(blank=True, related_name="won_games", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
