# Generated by Django 5.1 on 2024-08-12 03:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="friends",
            field=models.ManyToManyField(blank=True, related_name="followers", to=settings.AUTH_USER_MODEL),
        ),
    ]
