# Generated by Django 5.1 on 2024-08-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_friends"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="friends",
            new_name="followings",
        ),
    ]
